set `LP_REWARD` on poolpair
DeFiCh/playground pull request #134
Opened 2021-08-06 09:22 UTC by canonbrother

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
added **LP_REWARD** on poolpair

#### Which issue(s) does this PR fixes?:

Fixes # 133

2021-08-06 09:37 UTC, fuxingloh requested changes

2021-08-06 09:37 UTC, fuxingloh commented on src/module.playground/setup/setup.dex.ts
> +      await this.generate(1)
logic should be at `create`

2021-08-06 09:37 UTC, monstrobishi approved these changes

2021-08-06 09:38 UTC, monstrobishi commented
would be good to add a test to confirm that it comes through in `rewardPct`

2021-08-06 10:06 UTC, canonbrother commented on src/module.playground/setup/setup.dex.ts
> +      await this.generate(1)
just realize it's required another implemetation to allow reward is fairly divided to each poolpair.
```
1. setgov `tokenId: 0.2` on first poolpair -> err as reward must be 1
2. place setgov `tokenId: 1` on create() -> no err but only the last poolpair contains reward
```

2021-08-06 10:13 UTC, fuxingloh commented on src/module.playground/setup/setup.dex.ts
> +      await this.generate(1)
We need another `setup.rewards.ts`?

2021-08-06 10:26 UTC, canonbrother commented
WIP

2021-08-06 14:02 UTC, canonbrother commented on src/module.playground/setup/setup.dex.ts
> +      await this.generate(1)
nope.. need make use of the `after()`
i did some refactoring

2021-08-07 07:40 UTC, fuxingloh requested changes

2021-08-07 07:40 UTC, fuxingloh commented on src/module.playground/setup/setup.dex.ts
> +  async after (list: PoolPairSetup[]): Promise<void> {
```suggestion
  protected async after (list: PoolPairSetup[]): Promise<void> {
```

They are meant to be overridable but optional, hence you don't need to declare if you don't need them.

2021-08-07 07:47 UTC, fuxingloh approved these changes

2021-08-07 07:49 UTC, merged