`set-oracle-data` bot
DeFiCh/playground pull request #190
Opened 2021-09-28 10:23 UTC by monstrobishi

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

Adds `set-oracle-data` bot

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-09-28 17:21 UTC, fuxingloh requested changes
Should also add a simple test to test the outcome of oracle price after block 250 or something.

2021-09-28 17:21 UTC, fuxingloh commented on src/module.playground/bot/oracle.bot.ts
> +        priceChange: new BigNumber(25),
Maybe we should use percentage change? So that the testing is more deterministic linearly e.g. 10% lesser always instead of chip away 25 by 25?

2021-09-28 17:21 UTC, fuxingloh commented on src/module.playground/bot/bot.ts
> +  abstract has (each: Each): Promise<boolean>
If we were to do `has`, we should only run it once. Or maybe don't have it.

2021-09-30 06:08 UTC, monstrobishi commented on src/module.playground/bot/bot.ts
> +  abstract has (each: Each): Promise<boolean>
It's necessary for this particular scenario as the oracles need coinbase maturity to be appointed, if set oracle data is run before this then it will spit out a lot of errors. I can't think of another way to structure this that isn't overly complex

2021-09-30 06:21 UTC, fuxingloh approved these changes

2021-09-30 06:58 UTC, merged